### ISSUE TITLE
Add the ability to unit test the various fields on the sendwithus request. 

### ISSUE THREAD

**Issue by Zambonilli** [sendwithus/sendwithus_nodejs#11]
While the test API key is nice and allows us to treat your service as a stub in testing, it's really difficult to  create unit tests for the various fields being sent to sendwithus.  For example, I'd like to test that our code is sending the correct email ID for a specific use case.  Other examples include testing if our app is sending the correct email_data variables for various use cases.

I'm thinking the best way to do this would be to have the sendwithus object be an EventEmitter with events:
      'request' = Event emitted right before the first attempt to send a request to sendwithus.  Payload of the event would be the request object.
      'response'  = Event emitted after all attempts to send to sendwithus.

These events could also be used by client logging libs.  I can do this and send a PR if you want.

**Comment by brandonb927** [comment]
just a friendly poke @Zambonilli to shoot us a PR of your work so it can be merged in :)

**Comment by Zambonilli** [comment]
Merged with https://github.com/sendwithus/sendwithus_nodejs/pull/13
