### ISSUE TITLE
Differences in documented parameters

### ISSUE THREAD

**Issue by ilkka** [sendwithus/sendwithus_nodejs#26]
The README has examples for sending emails where `email_id` is used to select the template, but [the HTTP API docs](https://www.sendwithus.com/docs/api#sending-emails) use `template` instead. As far as I can tell, the options to the JS API are just passed through. Weirdly though, `email_id` also seems to work. Is there a documentation issue here somewhere?

**Comment by demoore** [comment]
Great question! They're interchangeable and we're moving toward's `template` for newer clients. Using `template` matches more closely with the Sendwithus Dashboard.
