### ISSUE TITLE
Update dependency to fix vulnerability

### ISSUE THREAD

**Issue by idris-maps** [sendwithus/sendwithus_nodejs#44]
### Client version

4.3.0

### Expected behaviour

No vulnerabilities

### Actual behaviour

![Screenshot from 2020-02-17 14-33-42](https://user-images.githubusercontent.com/12154856/74658750-36397900-5193-11ea-94b9-b6ddcf7a475d.png)

### Steps to reproduce

```bash
npm install
```

**Comment by demoore** [comment]
Thanks for reporting this @idris-maps. We'll update this as soon as this has been merged into the HTTP client this package uses: https://github.com/danwrong/restler/pull/263

**Comment by vuhrmeister** [comment]
Are you confident that it will? The last commit is from 2015 and there are a lot of outstanding Pull Requests.

**Comment by idris-maps** [comment]
It seems to be a library to do HTTP requests. Maybe it makes sense to use something that is actively maintained. Maybe [axios](https://github.com/axios/axios)

**Comment by demoore** [comment]
Yeah, that's a good point. I don't think we're able to rewrite the client with a different dependency soon. I wonder if we can vendor restler and and update the package the vulnerability?

**Comment by tday** [comment]
Any updates on this? Seems just a few steps away given you've forked and patched

**Comment by demoore** [comment]
Thank you for your patience, folks. We've released a new version with a patched version of restler.

**Comment by tday** [comment]
Thanks so much for the patch! @demoore 👏
