### ISSUE TITLE
restler dependency is very outdated

### ISSUE THREAD

**Issue by matthewmayer** [sendwithus/sendwithus_nodejs#49]
### Client version
4.3.2

### Expected behaviour
installing sendwithus installs a minimal number of packages. 

### Actual behaviour
` npm i sendwithus` depends on restler, which hasnt been updated for 6 years, and depends on a large number of packages, many of which report security issues.

```
up to date, audited 314 packages in 8s

33 vulnerabilities (11 low, 13 moderate, 8 high, 1 critical)

To address all issues, run:
  npm audit fix
```

Suggest to switch from restler to something like `node-fetch`

### Steps to reproduce
`npm i sendwithus`

**Comment by dlsteuer** [comment]
@matthewmayer thanks for bringing this to our attention, we'll slot this in an upcoming sprint to update.
