### ISSUE TITLE
`sendWithUs.send` Does not call callback when there is a network error

### ISSUE THREAD

**Issue by neil176** [sendwithus/sendwithus_nodejs#58]
### Client version

5.1.0

### Expected behaviour

The callback passed to `sendWithUs.send(data, callback)` should always be called

### Actual behaviour

The callback is not called when there is an error that prevents any response from the server (such as `ETIMEDOUT`)

### Steps to reproduce

Induce a network error in the request flow.

### Recommendation

A `.catch(err => callback(err)` or similar should be added to:

https://github.com/sendwithus/sendwithus_nodejs/blob/master/lib/sendwithus.js#L150-L154

**Comment by rob-swu** [comment]
Thanks for bringing this to our attention. We will add this within the next two weeks, I'll link back to the issue with the PR when it's available

**Comment by rob-swu** [comment]
this has been covered in the [6.0.0 release](https://github.com/sendwithus/sendwithus_nodejs/releases/tag/v6.0.0) done in PR #61
