### ISSUE TITLE
Cannot read property 'ok' of undefined in sendwithus.js

### ISSUE THREAD

**Issue by thomasInes** [sendwithus/sendwithus_nodejs#64]
Hi,

does the API have an issue this morning?
The library has started to throw errors in our app. It seems the API is not sending what the library expects (cf error below).
We didn't observe this behavior with this version of the library before.
Thank you :)

### Client version
6.0.1

### Expected behaviour
no error thrown

### Actual behaviour
error being thrown by the library:
```
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "TypeError: Cannot read property 'ok' of undefined",
    "reason": {
        "errorType": "TypeError",
        "errorMessage": "Cannot read property 'ok' of undefined",
        "stack": [
            "TypeError: Cannot read property 'ok' of undefined",
            "    at Sendwithus._handleResponse (/var/task/node_modules/sendwithus/lib/sendwithus.js:122:23)",
            "    at /var/task/node_modules/sendwithus/lib/sendwithus.js:91:63",
            "    at propagateAslWrapper (/var/task/node_modules/async-listener/index.js:504:23)",
            "    at proxyWrapper (/var/task/node_modules/async-listener/index.js:531:16)",
            "    at /var/task/node_modules/async-listener/index.js:541:70",
            "    at /var/task/node_modules/async-listener/glue.js:188:31",
            "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: TypeError: Cannot read property 'ok' of undefined",
        "    at process.<anonymous> (/var/runtime/index.js:35:15)",
        "    at process.emit (events.js:314:20)",
        "    at process.EventEmitter.emit (domain.js:483:12)",
        "    at processPromiseRejections (internal/process/promises.js:209:33)",
        "    at processTicksAndRejections (internal/process/task_queues.js:98:32)"
    ]
}
```

### Steps to reproduce
not sure. either calling `send` or `render`

**Comment by demoore** [comment]
Hmm, this could be a result of an issue on the API or network issue, but I think something else is going on. We're taking a look. Thanks for reporting this!

**Comment by thomasInes** [comment]
@demoore thanks for looking into this.
FWI, if that can help, the emails related to these calls seem to have been processed and sent successfully by SWU.

**Comment by thomasInes** [comment]
Thank you @demoore. Will upgrade and monitor the lib's behavior.

Just out of curiosity though, if the issue is network or API related, how would your update help?
And if it not, should it not means the lib should error out all the time? In our case it errors out randomly (but more frequently these past few days). Just trying to understand.
Thanks again

**Comment by demoore** [comment]
I don't think it's network related. I was able to reproduce the same error with some pretty basic code:
```javascript
api.render({ template: TEMPLATE_ID }, (r) => {
  console.log(r); // this worked
  console.log(Object.keys(r)); // this did NOT
});
```
I think this was happening in specific cases where the render/send callback was trying to access the response object. Without seeing your code it's tough to say for sure  -- especially since we didn't have any API alarms go off.

Keep me posted on whether the issue persists! If so, we might have to get you to reach out to our support so we can trace your account.

**Comment by thomasInes** [comment]
Thank you. Will keep you posted
